# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hS_uFBBjimI9gE4UkQ-qOBBVvE6xK6_
"""

class DataScience:
      subject="Pandas"
      def getInfo(self):
          print(f"Name of student is {self.name}")
          print(f"Duration of course in days:{self.duration}")

a=DataScience()
a.name="Purvi"
a.duration=20
a.getInfo()

class Employee():
    company="IBM"
    salary=30000

Mahi=Employee()
Sam=Employee()
Mahi.Salary=23000
Sam.Salary=55000
print("Mahi Salary is :",Mahi.Salary)
print("Sam Salary is :",Sam.salary)

#staticmethod

class Employee:
   company="IBM"

   @staticmethod
   def greet():
       print("Thanks for coming....")

Mohit=Employee()
Mohit.greet()

#init

class Employee():
    company="IBM"
    def __init__(self,name,salary,designation):
       self.name=name
       self.salary=salary
       self.designation=designation
    def getInfo(self):
        print(f"Name of the employee is :{self.name}")
        print(f"Salary of the employee is :{self.salary}")
        print(f"Designation of the employee is :{self.designation}")

a=Employee("Vinu",5000000,"Java Developer")
a.getInfo()

class Calculator():
    def __init__(self,num):
        self.number=num
    def square(self):
        print(f"The value{self.number} of square is {self.number**2}")
    def squareRoot(self):
        print(f"The value{self.number} of squareroot is {self.number**0.5}")
    def cube(self):
        print(f"The value{self.number} of the cube is {self.number**3}")

a=Calculator(3)
a.square()
a.squareRoot()
a.cube()

class Employee():
    company="IBM"

    def showDetails(self):
        print("He is an employee...")
class Programmer(Employee):
    language="python"

    def getLanguage(self):
        print(f"The Language is {self.language}")
e=Employee()
e.showDetails()
p=Programmer()
p.showDetails()
p.getLanguage

class Dominos():
    location='Jaipur'

    def __init__(self,item,quantity,price):
        self.itemname=item
        self.quantity=quantity
        self.price=price

    def getInfo(self):
        print(f"Nme of item is :{self.itemname}")
        print(f"Quantity of item are :{self.quantity}")
        print(f"Price of single item is :{self.price}")
        if(self.quantity*self.price)>1000:
            print(f"Total Bill is :{(self.quantity*self.price)-(0.2*self.quantity*self.price)}")

a=Dominos('Burger',2,600)
a.getInfo()

